{
  "extends":
    [
      "eslint:recommended",
      "plugin:@typescript-eslint/eslint-recommended",
      "plugin:@typescript-eslint/recommended",
      "airbnb-base",
      "plugin:jest/recommended",
      "prettier",
      "prettier/@typescript-eslint",
    ],
  "settings":
    { "import/resolver": { "node": { "extensions": [".js", ".ts"] } } },
}
